[package]
name = "ecdsa_wasm"
version = "0.1.0"

authors = ["brendon <brendon@litprotocol.com>"]
description = "WASM friendly recombination code for threshold ECDSA."
homepage = "https://github.com/lit-protocol"
license = "GPL-3.0-or-later"

[features]
default = ["wee_alloc"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"] }
web-sys = { version = "0.3.5", features = ["console"] }

#rand = { version = "0.6" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

num-bigint = { version = "0.2.2", features = ["serde", "rand"] }
num-integer = "0.1"
num-traits = "0.2.6"

# bit-vec = "0.5"
# cryptoxide = "0.1.1"
# hmac = "0.12.1"
# hmac = "0.7"
zeroize = "0.5.2"
libsecp256k1 = "0.3"
k256 = "0.9.5"
hex = "0.4.3"
# [dependencies.rand]
# getrandom = { version = "0.2", features = ["js"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = false }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

getrandom = { version = "0.2", features = ["js"] }

[dependencies.rand]
version = "0.6"
package = "rand"

[profile.release]
lto = true
opt-level = "z"
